services:
  charsibot-discord:
    build: ./discord
    container_name: discord
    restart: unless-stopped
    environment:
      - DISCORD_APP_ID
      - DISCORD_GUILD_ID
      - DISCORD_TOKEN

  charsibot-twitch:
    build:
      context: .
      dockerfile: ./twitch/Dockerfile
    container_name: twitch
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - LOG_LEVEL
      - WS_PORT=8081
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
      - TWITCH_OAUTH_TOKEN
      - TWITCH_REFRESH_TOKEN
      - TWITCH_BOT_OAUTH_TOKEN
      - TWITCH_BOT_REFRESH_TOKEN
      - TWITCH_BOT_USER_ID
      - TWITCH_CHANNEL_USER_ID
      - TURSO_DATABASE_URL
      - TURSO_AUTH_TOKEN

  twitch-overlay:
    build:
      context: .
      dockerfile: ./twitch-overlay/Dockerfile
    container_name: twitch-overlay
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - charsibot-twitch
    environment:
      - PUBLIC_TWITCH_WEBSOCKET_URL
