services:
  charsibot-discord:
    build: ./discord
    container_name: charsibot-discord
    env_file: ./discord/.env
    restart: unless-stopped

  charsibot-twitch:
    build: ./twitch
    container_name: charsibot-twitch
    env_file: ./twitch/.env
    restart: unless-stopped
    volumes:
      - ./twitch/logs:/var/log/charsibot-twitch
    healthcheck:
      test: ["CMD", "pgrep", "-f", "./main"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
