services:
  charsibot-discord:
    build: ./discord
    container_name: discord
    restart: unless-stopped
    environment:
      - DISCORD_APP_ID
      - DISCORD_GUILD_ID
      - DISCORD_TOKEN

  charsibot-twitch:
    build: ./twitch
    container_name: twitch
    restart: unless-stopped
    environment:
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
      - TWITCH_OAUTH_TOKEN
      - TWITCH_REFRESH_TOKEN
      - TWITCH_BOT_OAUTH_TOKEN
      - TWITCH_BOT_REFRESH_TOKEN
      - TWITCH_BOT_USER_ID
      - TWITCH_CHANNEL_USER_ID
      - TURSO_DATABASE_URL
      - TURSO_AUTH_TOKEN
    volumes:
      - ./twitch/logs:/var/log/charsibot-twitch
    healthcheck:
      test: ["CMD", "pgrep", "-f", "./main"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
