services:
  discord:
    build:
      context: ./apps/discord
      dockerfile: ./Dockerfile
    container_name: discord
    restart: unless-stopped
    environment:
      - DISCORD_CLIENT_ID
      - DISCORD_GUILD_ID
      - DISCORD_TOKEN

  twitch:
    build:
      context: ./apps/twitch
      dockerfile: ./Dockerfile
    container_name: twitch
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - twitch-data:/data
    environment:
      - LOG_LEVEL
      - WS_PORT=8081
      - DB_PATH=/data/charsibot.db
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
      - TWITCH_OAUTH_TOKEN
      - TWITCH_REFRESH_TOKEN
      - TWITCH_BOT_OAUTH_TOKEN
      - TWITCH_BOT_REFRESH_TOKEN
      - TWITCH_BOT_USER_ID
      - TWITCH_CHANNEL_USER_ID

  twitch-overlay:
    build:
      context: ./apps/twitch-overlay
      dockerfile: ./Dockerfile
    container_name: twitch-overlay
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - twitch
    environment:
      - PUBLIC_TWITCH_WEBSOCKET_URL

volumes:
  twitch-data:
