services:
  charsibot-discord:
    build: ./discord
    container_name: discord
    restart: unless-stopped
    environment:
      - DISCORD_APP_ID
      - DISCORD_GUILD_ID
      - DISCORD_TOKEN

  charsibot-twitch:
    build: ./twitch
    container_name: twitch
    restart: unless-stopped
    environment:
      - LOG_LEVEL
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
      - TWITCH_OAUTH_TOKEN
      - TWITCH_REFRESH_TOKEN
      - TWITCH_BOT_OAUTH_TOKEN
      - TWITCH_BOT_REFRESH_TOKEN
      - TWITCH_BOT_USER_ID
      - TWITCH_CHANNEL_USER_ID
      - DB_PATH=/data/charsibot.db
    volumes:
      - twitch-data:/data

volumes:
  twitch-data:
