/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/admin/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list-admin-users'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userID}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get-admin-user'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userID}/collections/{series}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['reset-admin-collection'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userID}/collections/{series}/display': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['display-admin-collection'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userID}/collections/{series}/random': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['grant-admin-random-plushie'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userID}/collections/{series}/{key}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['grant-admin-plushie'];
    post?: never;
    delete: operations['remove-admin-plushie'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userID}/stats/display': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['display-admin-stats'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userID}/stats/explode': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['explode-admin-user'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userID}/stats/explode/undo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['undo-admin-explode'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userID}/stats/random': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['grant-admin-random-stat'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userID}/stats/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['reset-admin-stats'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userID}/stats/{statName}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['update-admin-stat'];
    trace?: never;
  };
  '/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Stream overlay events */
    get: operations['overlay-events'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AdminChatInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AdminChatInputBody.json
       */
      readonly $schema?: string;
      displayInChat: boolean;
    };
    AdminCollection: {
      collected: string[];
      config: components['schemas']['SeriesConfig'];
    };
    AdminPlushieInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AdminPlushieInputBody.json
       */
      readonly $schema?: string;
      triggerOverlay: boolean;
    };
    AdminRandomPlushieInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AdminRandomPlushieInputBody.json
       */
      readonly $schema?: string;
      triggerOverlay: boolean;
    };
    AdminStat: {
      longName: string;
      /** @description Stable stat identifier */
      name: string;
      shortName: string;
      /** Format: int64 */
      value: number;
    };
    AdminStatInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AdminStatInputBody.json
       */
      readonly $schema?: string;
      /** @enum {string} */
      mode: 'set' | 'adjust';
      /** Format: int64 */
      value: number;
    };
    AdminUserResponse: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AdminUserResponse.json
       */
      readonly $schema?: string;
      collections: components['schemas']['AdminCollection'][];
      stats: components['schemas']['AdminStat'][];
      user: components['schemas']['User'];
    };
    AdminUsersResponse: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AdminUsersResponse.json
       */
      readonly $schema?: string;
      users: components['schemas']['User'][];
    };
    BlindBoxDisplayData: {
      collection: string[];
      config: components['schemas']['SeriesConfig'];
      username: string;
    };
    BlindBoxRedemptionData: {
      collection: string[];
      config: components['schemas']['SeriesConfig'];
      isNew: boolean;
      plushie: components['schemas']['Plushie'];
      username: string;
    };
    ChatCommandData: {
      message: string;
    };
    ErrorDetail: {
      /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
      location?: string;
      /** @description Error message text */
      message?: string;
      /** @description The value at the given location */
      value?: unknown;
    };
    ErrorModel: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ErrorModel.json
       */
      readonly $schema?: string;
      /**
       * @description A human-readable explanation specific to this occurrence of the problem.
       * @example Property foo is required but is missing.
       */
      detail?: string;
      /** @description Optional list of individual error details */
      errors?: components['schemas']['ErrorDetail'][] | null;
      /**
       * Format: uri
       * @description A URI reference that identifies the specific occurrence of the problem.
       * @example https://example.com/error-log/abc123
       */
      instance?: string;
      /**
       * Format: int64
       * @description HTTP status code
       * @example 400
       */
      status?: number;
      /**
       * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
       * @example Bad Request
       */
      title?: string;
      /**
       * Format: uri
       * @description A URI reference to human-readable documentation for the error.
       * @default about:blank
       * @example https://example.com/errors/example
       */
      type: string;
    };
    Plushie: {
      emptyImage: string;
      image: string;
      key: string;
      name: string;
      series: string;
      /** Format: int64 */
      sortOrder: number;
      /** Format: int64 */
      weight: number;
    };
    SeriesConfig: {
      boxFrontFace: string;
      boxSideFace: string;
      displayColor: string;
      name: string;
      plushies: components['schemas']['Plushie'][];
      redemptionTitle: string;
      revealSound: string;
      series: string;
      textColor: string;
    };
    User: {
      id: string;
      username: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'list-admin-users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUsersResponse'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'get-admin-user': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Twitch user ID */
        userID: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'reset-admin-collection': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userID: string;
        series: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'display-admin-collection': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userID: string;
        series: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'grant-admin-random-plushie': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userID: string;
        series: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminRandomPlushieInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'grant-admin-plushie': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userID: string;
        series: string;
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminPlushieInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'remove-admin-plushie': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userID: string;
        series: string;
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'display-admin-stats': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Twitch user ID */
        userID: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'explode-admin-user': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Twitch user ID */
        userID: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'undo-admin-explode': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Twitch user ID */
        userID: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'grant-admin-random-stat': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userID: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminChatInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'reset-admin-stats': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userID: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminChatInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'update-admin-stat': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userID: string;
        statName: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminStatInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'overlay-events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': (
            | {
                data: components['schemas']['BlindBoxDisplayData'];
                /**
                 * @description The event name.
                 * @constant
                 */
                event: 'blindbox_display';
                /** @description The event ID. */
                id?: number;
                /** @description The retry time in milliseconds. */
                retry?: number;
              }
            | {
                data: components['schemas']['BlindBoxRedemptionData'];
                /**
                 * @description The event name.
                 * @constant
                 */
                event: 'blindbox_redemption';
                /** @description The event ID. */
                id?: number;
                /** @description The retry time in milliseconds. */
                retry?: number;
              }
            | {
                data: components['schemas']['ChatCommandData'];
                /**
                 * @description The event name.
                 * @constant
                 */
                event: 'chat_command';
                /** @description The event ID. */
                id?: number;
                /** @description The retry time in milliseconds. */
                retry?: number;
              }
          )[];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
}
