// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.ensureUserStatsStmt, err = db.PrepareContext(ctx, ensureUserStats); err != nil {
		return nil, fmt.Errorf("error preparing query EnsureUserStats: %w", err)
	}
	if q.getAllSeriesStmt, err = db.PrepareContext(ctx, getAllSeries); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllSeries: %w", err)
	}
	if q.getAllSeriesWithPlushiesStmt, err = db.PrepareContext(ctx, getAllSeriesWithPlushies); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllSeriesWithPlushies: %w", err)
	}
	if q.getCollectedPlushiesStmt, err = db.PrepareContext(ctx, getCollectedPlushies); err != nil {
		return nil, fmt.Errorf("error preparing query GetCollectedPlushies: %w", err)
	}
	if q.getCompletedCollectionsStmt, err = db.PrepareContext(ctx, getCompletedCollections); err != nil {
		return nil, fmt.Errorf("error preparing query GetCompletedCollections: %w", err)
	}
	if q.getPlushiesForSeriesStmt, err = db.PrepareContext(ctx, getPlushiesForSeries); err != nil {
		return nil, fmt.Errorf("error preparing query GetPlushiesForSeries: %w", err)
	}
	if q.getRandomStatDefinitionStmt, err = db.PrepareContext(ctx, getRandomStatDefinition); err != nil {
		return nil, fmt.Errorf("error preparing query GetRandomStatDefinition: %w", err)
	}
	if q.getSeriesByTypeStmt, err = db.PrepareContext(ctx, getSeriesByType); err != nil {
		return nil, fmt.Errorf("error preparing query GetSeriesByType: %w", err)
	}
	if q.getStatDefinitionsStmt, err = db.PrepareContext(ctx, getStatDefinitions); err != nil {
		return nil, fmt.Errorf("error preparing query GetStatDefinitions: %w", err)
	}
	if q.getStatLeaderboardStmt, err = db.PrepareContext(ctx, getStatLeaderboard); err != nil {
		return nil, fmt.Errorf("error preparing query GetStatLeaderboard: %w", err)
	}
	if q.getUserStatsStmt, err = db.PrepareContext(ctx, getUserStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserStats: %w", err)
	}
	if q.hasUserPlushieStmt, err = db.PrepareContext(ctx, hasUserPlushie); err != nil {
		return nil, fmt.Errorf("error preparing query HasUserPlushie: %w", err)
	}
	if q.insertUserPlushieIfNewStmt, err = db.PrepareContext(ctx, insertUserPlushieIfNew); err != nil {
		return nil, fmt.Errorf("error preparing query InsertUserPlushieIfNew: %w", err)
	}
	if q.lastChangeCountStmt, err = db.PrepareContext(ctx, lastChangeCount); err != nil {
		return nil, fmt.Errorf("error preparing query LastChangeCount: %w", err)
	}
	if q.modifyStatValueStmt, err = db.PrepareContext(ctx, modifyStatValue); err != nil {
		return nil, fmt.Errorf("error preparing query ModifyStatValue: %w", err)
	}
	if q.resetUserPlushiesStmt, err = db.PrepareContext(ctx, resetUserPlushies); err != nil {
		return nil, fmt.Errorf("error preparing query ResetUserPlushies: %w", err)
	}
	if q.setStatValueStmt, err = db.PrepareContext(ctx, setStatValue); err != nil {
		return nil, fmt.Errorf("error preparing query SetStatValue: %w", err)
	}
	if q.updateUsernameStmt, err = db.PrepareContext(ctx, updateUsername); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUsername: %w", err)
	}
	if q.upsertUserPlushieStmt, err = db.PrepareContext(ctx, upsertUserPlushie); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertUserPlushie: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.ensureUserStatsStmt != nil {
		if cerr := q.ensureUserStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing ensureUserStatsStmt: %w", cerr)
		}
	}
	if q.getAllSeriesStmt != nil {
		if cerr := q.getAllSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllSeriesStmt: %w", cerr)
		}
	}
	if q.getAllSeriesWithPlushiesStmt != nil {
		if cerr := q.getAllSeriesWithPlushiesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllSeriesWithPlushiesStmt: %w", cerr)
		}
	}
	if q.getCollectedPlushiesStmt != nil {
		if cerr := q.getCollectedPlushiesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCollectedPlushiesStmt: %w", cerr)
		}
	}
	if q.getCompletedCollectionsStmt != nil {
		if cerr := q.getCompletedCollectionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCompletedCollectionsStmt: %w", cerr)
		}
	}
	if q.getPlushiesForSeriesStmt != nil {
		if cerr := q.getPlushiesForSeriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPlushiesForSeriesStmt: %w", cerr)
		}
	}
	if q.getRandomStatDefinitionStmt != nil {
		if cerr := q.getRandomStatDefinitionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRandomStatDefinitionStmt: %w", cerr)
		}
	}
	if q.getSeriesByTypeStmt != nil {
		if cerr := q.getSeriesByTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSeriesByTypeStmt: %w", cerr)
		}
	}
	if q.getStatDefinitionsStmt != nil {
		if cerr := q.getStatDefinitionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStatDefinitionsStmt: %w", cerr)
		}
	}
	if q.getStatLeaderboardStmt != nil {
		if cerr := q.getStatLeaderboardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStatLeaderboardStmt: %w", cerr)
		}
	}
	if q.getUserStatsStmt != nil {
		if cerr := q.getUserStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStatsStmt: %w", cerr)
		}
	}
	if q.hasUserPlushieStmt != nil {
		if cerr := q.hasUserPlushieStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing hasUserPlushieStmt: %w", cerr)
		}
	}
	if q.insertUserPlushieIfNewStmt != nil {
		if cerr := q.insertUserPlushieIfNewStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertUserPlushieIfNewStmt: %w", cerr)
		}
	}
	if q.lastChangeCountStmt != nil {
		if cerr := q.lastChangeCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing lastChangeCountStmt: %w", cerr)
		}
	}
	if q.modifyStatValueStmt != nil {
		if cerr := q.modifyStatValueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing modifyStatValueStmt: %w", cerr)
		}
	}
	if q.resetUserPlushiesStmt != nil {
		if cerr := q.resetUserPlushiesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resetUserPlushiesStmt: %w", cerr)
		}
	}
	if q.setStatValueStmt != nil {
		if cerr := q.setStatValueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setStatValueStmt: %w", cerr)
		}
	}
	if q.updateUsernameStmt != nil {
		if cerr := q.updateUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUsernameStmt: %w", cerr)
		}
	}
	if q.upsertUserPlushieStmt != nil {
		if cerr := q.upsertUserPlushieStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertUserPlushieStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	tx                           *sql.Tx
	ensureUserStatsStmt          *sql.Stmt
	getAllSeriesStmt             *sql.Stmt
	getAllSeriesWithPlushiesStmt *sql.Stmt
	getCollectedPlushiesStmt     *sql.Stmt
	getCompletedCollectionsStmt  *sql.Stmt
	getPlushiesForSeriesStmt     *sql.Stmt
	getRandomStatDefinitionStmt  *sql.Stmt
	getSeriesByTypeStmt          *sql.Stmt
	getStatDefinitionsStmt       *sql.Stmt
	getStatLeaderboardStmt       *sql.Stmt
	getUserStatsStmt             *sql.Stmt
	hasUserPlushieStmt           *sql.Stmt
	insertUserPlushieIfNewStmt   *sql.Stmt
	lastChangeCountStmt          *sql.Stmt
	modifyStatValueStmt          *sql.Stmt
	resetUserPlushiesStmt        *sql.Stmt
	setStatValueStmt             *sql.Stmt
	updateUsernameStmt           *sql.Stmt
	upsertUserPlushieStmt        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		ensureUserStatsStmt:          q.ensureUserStatsStmt,
		getAllSeriesStmt:             q.getAllSeriesStmt,
		getAllSeriesWithPlushiesStmt: q.getAllSeriesWithPlushiesStmt,
		getCollectedPlushiesStmt:     q.getCollectedPlushiesStmt,
		getCompletedCollectionsStmt:  q.getCompletedCollectionsStmt,
		getPlushiesForSeriesStmt:     q.getPlushiesForSeriesStmt,
		getRandomStatDefinitionStmt:  q.getRandomStatDefinitionStmt,
		getSeriesByTypeStmt:          q.getSeriesByTypeStmt,
		getStatDefinitionsStmt:       q.getStatDefinitionsStmt,
		getStatLeaderboardStmt:       q.getStatLeaderboardStmt,
		getUserStatsStmt:             q.getUserStatsStmt,
		hasUserPlushieStmt:           q.hasUserPlushieStmt,
		insertUserPlushieIfNewStmt:   q.insertUserPlushieIfNewStmt,
		lastChangeCountStmt:          q.lastChangeCountStmt,
		modifyStatValueStmt:          q.modifyStatValueStmt,
		resetUserPlushiesStmt:        q.resetUserPlushiesStmt,
		setStatValueStmt:             q.setStatValueStmt,
		updateUsernameStmt:           q.updateUsernameStmt,
		upsertUserPlushieStmt:        q.upsertUserPlushieStmt,
	}
}
