// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.ensureUserStatStmt, err = db.PrepareContext(ctx, ensureUserStat); err != nil {
		return nil, fmt.Errorf("error preparing query EnsureUserStat: %w", err)
	}
	if q.getAllUserStatValuesStmt, err = db.PrepareContext(ctx, getAllUserStatValues); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUserStatValues: %w", err)
	}
	if q.getCollectedPlushiesStmt, err = db.PrepareContext(ctx, getCollectedPlushies); err != nil {
		return nil, fmt.Errorf("error preparing query GetCollectedPlushies: %w", err)
	}
	if q.getUserPlushieCountsStmt, err = db.PrepareContext(ctx, getUserPlushieCounts); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserPlushieCounts: %w", err)
	}
	if q.getUserStatValuesStmt, err = db.PrepareContext(ctx, getUserStatValues); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserStatValues: %w", err)
	}
	if q.hasUserPlushieStmt, err = db.PrepareContext(ctx, hasUserPlushie); err != nil {
		return nil, fmt.Errorf("error preparing query HasUserPlushie: %w", err)
	}
	if q.insertUserPlushieIfNewStmt, err = db.PrepareContext(ctx, insertUserPlushieIfNew); err != nil {
		return nil, fmt.Errorf("error preparing query InsertUserPlushieIfNew: %w", err)
	}
	if q.lastChangeCountStmt, err = db.PrepareContext(ctx, lastChangeCount); err != nil {
		return nil, fmt.Errorf("error preparing query LastChangeCount: %w", err)
	}
	if q.modifyStatValueStmt, err = db.PrepareContext(ctx, modifyStatValue); err != nil {
		return nil, fmt.Errorf("error preparing query ModifyStatValue: %w", err)
	}
	if q.resetUserPlushiesStmt, err = db.PrepareContext(ctx, resetUserPlushies); err != nil {
		return nil, fmt.Errorf("error preparing query ResetUserPlushies: %w", err)
	}
	if q.setStatValueStmt, err = db.PrepareContext(ctx, setStatValue); err != nil {
		return nil, fmt.Errorf("error preparing query SetStatValue: %w", err)
	}
	if q.updateUsernameStmt, err = db.PrepareContext(ctx, updateUsername); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUsername: %w", err)
	}
	if q.upsertUserPlushieStmt, err = db.PrepareContext(ctx, upsertUserPlushie); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertUserPlushie: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.ensureUserStatStmt != nil {
		if cerr := q.ensureUserStatStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing ensureUserStatStmt: %w", cerr)
		}
	}
	if q.getAllUserStatValuesStmt != nil {
		if cerr := q.getAllUserStatValuesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUserStatValuesStmt: %w", cerr)
		}
	}
	if q.getCollectedPlushiesStmt != nil {
		if cerr := q.getCollectedPlushiesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCollectedPlushiesStmt: %w", cerr)
		}
	}
	if q.getUserPlushieCountsStmt != nil {
		if cerr := q.getUserPlushieCountsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserPlushieCountsStmt: %w", cerr)
		}
	}
	if q.getUserStatValuesStmt != nil {
		if cerr := q.getUserStatValuesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStatValuesStmt: %w", cerr)
		}
	}
	if q.hasUserPlushieStmt != nil {
		if cerr := q.hasUserPlushieStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing hasUserPlushieStmt: %w", cerr)
		}
	}
	if q.insertUserPlushieIfNewStmt != nil {
		if cerr := q.insertUserPlushieIfNewStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertUserPlushieIfNewStmt: %w", cerr)
		}
	}
	if q.lastChangeCountStmt != nil {
		if cerr := q.lastChangeCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing lastChangeCountStmt: %w", cerr)
		}
	}
	if q.modifyStatValueStmt != nil {
		if cerr := q.modifyStatValueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing modifyStatValueStmt: %w", cerr)
		}
	}
	if q.resetUserPlushiesStmt != nil {
		if cerr := q.resetUserPlushiesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resetUserPlushiesStmt: %w", cerr)
		}
	}
	if q.setStatValueStmt != nil {
		if cerr := q.setStatValueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setStatValueStmt: %w", cerr)
		}
	}
	if q.updateUsernameStmt != nil {
		if cerr := q.updateUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUsernameStmt: %w", cerr)
		}
	}
	if q.upsertUserPlushieStmt != nil {
		if cerr := q.upsertUserPlushieStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertUserPlushieStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                         DBTX
	tx                         *sql.Tx
	ensureUserStatStmt         *sql.Stmt
	getAllUserStatValuesStmt   *sql.Stmt
	getCollectedPlushiesStmt   *sql.Stmt
	getUserPlushieCountsStmt   *sql.Stmt
	getUserStatValuesStmt      *sql.Stmt
	hasUserPlushieStmt         *sql.Stmt
	insertUserPlushieIfNewStmt *sql.Stmt
	lastChangeCountStmt        *sql.Stmt
	modifyStatValueStmt        *sql.Stmt
	resetUserPlushiesStmt      *sql.Stmt
	setStatValueStmt           *sql.Stmt
	updateUsernameStmt         *sql.Stmt
	upsertUserPlushieStmt      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                         tx,
		tx:                         tx,
		ensureUserStatStmt:         q.ensureUserStatStmt,
		getAllUserStatValuesStmt:   q.getAllUserStatValuesStmt,
		getCollectedPlushiesStmt:   q.getCollectedPlushiesStmt,
		getUserPlushieCountsStmt:   q.getUserPlushieCountsStmt,
		getUserStatValuesStmt:      q.getUserStatValuesStmt,
		hasUserPlushieStmt:         q.hasUserPlushieStmt,
		insertUserPlushieIfNewStmt: q.insertUserPlushieIfNewStmt,
		lastChangeCountStmt:        q.lastChangeCountStmt,
		modifyStatValueStmt:        q.modifyStatValueStmt,
		resetUserPlushiesStmt:      q.resetUserPlushiesStmt,
		setStatValueStmt:           q.setStatValueStmt,
		updateUsernameStmt:         q.updateUsernameStmt,
		upsertUserPlushieStmt:      q.upsertUserPlushieStmt,
	}
}
