// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type UserPlushie struct {
	UserID   string `json:"userId"`
	Username string `json:"username"`
	Series   string `json:"series"`
	Key      string `json:"key"`
}

type UserStat struct {
	UserID   string `json:"userId"`
	Username string `json:"username"`
	StatName string `json:"statName"`
	Value    int64  `json:"value"`
}
