// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"
)

const ensureUserStat = `-- name: EnsureUserStat :exec
INSERT OR IGNORE INTO user_stats (user_id, username, stat_name, value)
VALUES (?, ?, ?, ?)
`

type EnsureUserStatParams struct {
	UserID   string `json:"userId"`
	Username string `json:"username"`
	StatName string `json:"statName"`
	Value    int64  `json:"value"`
}

func (q *Queries) EnsureUserStat(ctx context.Context, arg EnsureUserStatParams) error {
	_, err := q.exec(ctx, q.ensureUserStatStmt, ensureUserStat,
		arg.UserID,
		arg.Username,
		arg.StatName,
		arg.Value,
	)
	return err
}

const getAllUserStatValues = `-- name: GetAllUserStatValues :many
SELECT username, stat_name, value
FROM user_stats
`

type GetAllUserStatValuesRow struct {
	Username string `json:"username"`
	StatName string `json:"statName"`
	Value    int64  `json:"value"`
}

func (q *Queries) GetAllUserStatValues(ctx context.Context) ([]GetAllUserStatValuesRow, error) {
	rows, err := q.query(ctx, q.getAllUserStatValuesStmt, getAllUserStatValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUserStatValuesRow{}
	for rows.Next() {
		var i GetAllUserStatValuesRow
		if err := rows.Scan(&i.Username, &i.StatName, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStatValues = `-- name: GetUserStatValues :many
SELECT stat_name, value
FROM user_stats
WHERE user_id = ?
`

type GetUserStatValuesRow struct {
	StatName string `json:"statName"`
	Value    int64  `json:"value"`
}

func (q *Queries) GetUserStatValues(ctx context.Context, userID string) ([]GetUserStatValuesRow, error) {
	rows, err := q.query(ctx, q.getUserStatValuesStmt, getUserStatValues, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserStatValuesRow{}
	for rows.Next() {
		var i GetUserStatValuesRow
		if err := rows.Scan(&i.StatName, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modifyStatValue = `-- name: ModifyStatValue :exec
UPDATE user_stats SET value = value + ?
WHERE user_id = ? AND stat_name = ?
`

type ModifyStatValueParams struct {
	Value    int64  `json:"value"`
	UserID   string `json:"userId"`
	StatName string `json:"statName"`
}

func (q *Queries) ModifyStatValue(ctx context.Context, arg ModifyStatValueParams) error {
	_, err := q.exec(ctx, q.modifyStatValueStmt, modifyStatValue, arg.Value, arg.UserID, arg.StatName)
	return err
}

const setStatValue = `-- name: SetStatValue :exec
UPDATE user_stats SET value = ?
WHERE user_id = ? AND stat_name = ?
`

type SetStatValueParams struct {
	Value    int64  `json:"value"`
	UserID   string `json:"userId"`
	StatName string `json:"statName"`
}

func (q *Queries) SetStatValue(ctx context.Context, arg SetStatValueParams) error {
	_, err := q.exec(ctx, q.setStatValueStmt, setStatValue, arg.Value, arg.UserID, arg.StatName)
	return err
}

const updateUsername = `-- name: UpdateUsername :exec
UPDATE user_stats SET username = ? WHERE user_id = ?
`

type UpdateUsernameParams struct {
	Username string `json:"username"`
	UserID   string `json:"userId"`
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) error {
	_, err := q.exec(ctx, q.updateUsernameStmt, updateUsername, arg.Username, arg.UserID)
	return err
}
