// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blind_box.sql

package store

import (
	"context"
	"database/sql"
)

const getAllSeries = `-- name: GetAllSeries :many
SELECT series, redemption_title, name, reveal_sound, box_front_face, box_side_face, display_color, text_color FROM blind_box_series ORDER BY series
`

func (q *Queries) GetAllSeries(ctx context.Context) ([]BlindBoxSeries, error) {
	rows, err := q.query(ctx, q.getAllSeriesStmt, getAllSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlindBoxSeries{}
	for rows.Next() {
		var i BlindBoxSeries
		if err := rows.Scan(
			&i.Series,
			&i.RedemptionTitle,
			&i.Name,
			&i.RevealSound,
			&i.BoxFrontFace,
			&i.BoxSideFace,
			&i.DisplayColor,
			&i.TextColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSeriesWithPlushies = `-- name: GetAllSeriesWithPlushies :many
SELECT
  bbs.series,
  bbs.redemption_title,
  bbs.name,
  bbs.reveal_sound,
  bbs.box_front_face,
  bbs.box_side_face,
  bbs.display_color,
  bbs.text_color,
  bbp.id         AS plushie_id,
  bbp.key        AS plushie_key,
  bbp.sort_order AS plushie_sort_order,
  bbp.weight     AS plushie_weight,
  bbp.name       AS plushie_name,
  bbp.image      AS plushie_image,
  bbp.empty_image AS plushie_empty_image
FROM blind_box_series bbs
LEFT JOIN blind_box_plushies bbp ON bbp.series = bbs.series
ORDER BY bbs.series, bbp.sort_order
`

type GetAllSeriesWithPlushiesRow struct {
	Series            string         `json:"series"`
	RedemptionTitle   string         `json:"redemptionTitle"`
	Name              string         `json:"name"`
	RevealSound       string         `json:"revealSound"`
	BoxFrontFace      string         `json:"boxFrontFace"`
	BoxSideFace       string         `json:"boxSideFace"`
	DisplayColor      string         `json:"displayColor"`
	TextColor         string         `json:"textColor"`
	PlushieID         sql.NullInt64  `json:"plushieId"`
	PlushieKey        sql.NullString `json:"plushieKey"`
	PlushieSortOrder  sql.NullInt64  `json:"plushieSortOrder"`
	PlushieWeight     sql.NullInt64  `json:"plushieWeight"`
	PlushieName       sql.NullString `json:"plushieName"`
	PlushieImage      sql.NullString `json:"plushieImage"`
	PlushieEmptyImage sql.NullString `json:"plushieEmptyImage"`
}

func (q *Queries) GetAllSeriesWithPlushies(ctx context.Context) ([]GetAllSeriesWithPlushiesRow, error) {
	rows, err := q.query(ctx, q.getAllSeriesWithPlushiesStmt, getAllSeriesWithPlushies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllSeriesWithPlushiesRow{}
	for rows.Next() {
		var i GetAllSeriesWithPlushiesRow
		if err := rows.Scan(
			&i.Series,
			&i.RedemptionTitle,
			&i.Name,
			&i.RevealSound,
			&i.BoxFrontFace,
			&i.BoxSideFace,
			&i.DisplayColor,
			&i.TextColor,
			&i.PlushieID,
			&i.PlushieKey,
			&i.PlushieSortOrder,
			&i.PlushieWeight,
			&i.PlushieName,
			&i.PlushieImage,
			&i.PlushieEmptyImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlushiesForSeries = `-- name: GetPlushiesForSeries :many
SELECT id, series, "key", sort_order, weight, name, image, empty_image FROM blind_box_plushies WHERE series = ? ORDER BY sort_order
`

func (q *Queries) GetPlushiesForSeries(ctx context.Context, series string) ([]BlindBoxPlushie, error) {
	rows, err := q.query(ctx, q.getPlushiesForSeriesStmt, getPlushiesForSeries, series)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlindBoxPlushie{}
	for rows.Next() {
		var i BlindBoxPlushie
		if err := rows.Scan(
			&i.ID,
			&i.Series,
			&i.Key,
			&i.SortOrder,
			&i.Weight,
			&i.Name,
			&i.Image,
			&i.EmptyImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeriesByType = `-- name: GetSeriesByType :one
SELECT series, redemption_title, name, reveal_sound, box_front_face, box_side_face, display_color, text_color FROM blind_box_series WHERE series = ?
`

func (q *Queries) GetSeriesByType(ctx context.Context, series string) (BlindBoxSeries, error) {
	row := q.queryRow(ctx, q.getSeriesByTypeStmt, getSeriesByType, series)
	var i BlindBoxSeries
	err := row.Scan(
		&i.Series,
		&i.RedemptionTitle,
		&i.Name,
		&i.RevealSound,
		&i.BoxFrontFace,
		&i.BoxSideFace,
		&i.DisplayColor,
		&i.TextColor,
	)
	return i, err
}
