// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaderboards.sql

package store

import (
	"context"
)

const getStatLeaderboard = `-- name: GetStatLeaderboard :one
SELECT
  (SELECT username FROM stats ORDER BY strength DESC LIMIT 1)     AS top_strength_username,
  (SELECT strength FROM stats ORDER BY strength DESC LIMIT 1)     AS top_strength_value,

  (SELECT username FROM stats ORDER BY intelligence DESC LIMIT 1) AS top_intelligence_username,
  (SELECT intelligence FROM stats ORDER BY intelligence DESC LIMIT 1) AS top_intelligence_value,

  (SELECT username FROM stats ORDER BY charisma DESC LIMIT 1)     AS top_charisma_username,
  (SELECT charisma FROM stats ORDER BY charisma DESC LIMIT 1)     AS top_charisma_value,

  (SELECT username FROM stats ORDER BY luck DESC LIMIT 1)         AS top_luck_username,
  (SELECT luck FROM stats ORDER BY luck DESC LIMIT 1)             AS top_luck_value,

  (SELECT username FROM stats ORDER BY dexterity DESC LIMIT 1)    AS top_dexterity_username,
  (SELECT dexterity FROM stats ORDER BY dexterity DESC LIMIT 1)   AS top_dexterity_value,

  (SELECT username FROM stats ORDER BY penis DESC LIMIT 1)        AS top_penis_username,
  (SELECT penis FROM stats ORDER BY penis DESC LIMIT 1)           AS top_penis_value
`

type GetStatLeaderboardRow struct {
	TopStrengthUsername     string `json:"top_strength_username"`
	TopStrengthValue        int64  `json:"top_strength_value"`
	TopIntelligenceUsername string `json:"top_intelligence_username"`
	TopIntelligenceValue    int64  `json:"top_intelligence_value"`
	TopCharismaUsername     string `json:"top_charisma_username"`
	TopCharismaValue        int64  `json:"top_charisma_value"`
	TopLuckUsername         string `json:"top_luck_username"`
	TopLuckValue            int64  `json:"top_luck_value"`
	TopDexterityUsername    string `json:"top_dexterity_username"`
	TopDexterityValue       int64  `json:"top_dexterity_value"`
	TopPenisUsername        string `json:"top_penis_username"`
	TopPenisValue           int64  `json:"top_penis_value"`
}

func (q *Queries) GetStatLeaderboard(ctx context.Context) (GetStatLeaderboardRow, error) {
	row := q.queryRow(ctx, q.getStatLeaderboardStmt, getStatLeaderboard)
	var i GetStatLeaderboardRow
	err := row.Scan(
		&i.TopStrengthUsername,
		&i.TopStrengthValue,
		&i.TopIntelligenceUsername,
		&i.TopIntelligenceValue,
		&i.TopCharismaUsername,
		&i.TopCharismaValue,
		&i.TopLuckUsername,
		&i.TopLuckValue,
		&i.TopDexterityUsername,
		&i.TopDexterityValue,
		&i.TopPenisUsername,
		&i.TopPenisValue,
	)
	return i, err
}
