// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

type BlindBoxPlushie struct {
	ID         int64  `json:"id"`
	Series     string `json:"series"`
	Key        string `json:"key"`
	SortOrder  int64  `json:"sortOrder"`
	Weight     int64  `json:"weight"`
	Name       string `json:"name"`
	Image      string `json:"image"`
	EmptyImage string `json:"emptyImage"`
}

type BlindBoxSeries struct {
	Series          string `json:"series"`
	RedemptionTitle string `json:"redemptionTitle"`
	Name            string `json:"name"`
	RevealSound     string `json:"revealSound"`
	BoxFrontFace    string `json:"boxFrontFace"`
	BoxSideFace     string `json:"boxSideFace"`
	DisplayColor    string `json:"displayColor"`
	TextColor       string `json:"textColor"`
}

type StatDefinition struct {
	Name         string `json:"name"`
	ShortName    string `json:"shortName"`
	LongName     string `json:"longName"`
	DefaultValue int64  `json:"defaultValue"`
	SortOrder    int64  `json:"sortOrder"`
}

type UserPlushie struct {
	UserID   string `json:"userId"`
	Username string `json:"username"`
	Series   string `json:"series"`
	Key      string `json:"key"`
}

type UserStat struct {
	UserID   string `json:"userId"`
	Username string `json:"username"`
	StatName string `json:"statName"`
	Value    int64  `json:"value"`
}
