// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type OauthToken struct {
	TokenType    string          `json:"token_type"`
	AccessToken  string          `json:"access_token"`
	RefreshToken string          `json:"refresh_token"`
	UpdatedAt    sql.NullFloat64 `json:"updated_at"`
}

type Stat struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	Strength     int64  `json:"strength"`
	Intelligence int64  `json:"intelligence"`
	Charisma     int64  `json:"charisma"`
	Luck         int64  `json:"luck"`
	Dexterity    int64  `json:"dexterity"`
	Penis        int64  `json:"penis"`
}

type UserCollection struct {
	UserID         sql.NullString `json:"user_id"`
	Username       string         `json:"username"`
	CollectionType sql.NullString `json:"collection_type"`
	Reward1        sql.NullInt64  `json:"reward1"`
	Reward2        sql.NullInt64  `json:"reward2"`
	Reward3        sql.NullInt64  `json:"reward3"`
	Reward4        sql.NullInt64  `json:"reward4"`
	Reward5        sql.NullInt64  `json:"reward5"`
	Reward6        sql.NullInt64  `json:"reward6"`
	Reward7        sql.NullInt64  `json:"reward7"`
	Reward8        sql.NullInt64  `json:"reward8"`
}
