// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package store

import (
	"context"
)

const getStats = `-- name: GetStats :one
SELECT id, username, strength, intelligence, charisma, luck, dexterity, penis
FROM stats
WHERE id = ?
`

func (q *Queries) GetStats(ctx context.Context, id string) (Stat, error) {
	row := q.queryRow(ctx, q.getStatsStmt, getStats, id)
	var i Stat
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Strength,
		&i.Intelligence,
		&i.Charisma,
		&i.Luck,
		&i.Dexterity,
		&i.Penis,
	)
	return i, err
}

const modifyCharisma = `-- name: ModifyCharisma :exec
INSERT INTO stats (id, username)
VALUES (?, ?)
ON CONFLICT(id) DO NOTHING
`

type ModifyCharismaParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) ModifyCharisma(ctx context.Context, arg ModifyCharismaParams) error {
	_, err := q.exec(ctx, q.modifyCharismaStmt, modifyCharisma, arg.ID, arg.Username)
	return err
}

const modifyDexterity = `-- name: ModifyDexterity :exec
INSERT INTO stats (id, username)
VALUES (?, ?)
ON CONFLICT(id) DO NOTHING
`

type ModifyDexterityParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) ModifyDexterity(ctx context.Context, arg ModifyDexterityParams) error {
	_, err := q.exec(ctx, q.modifyDexterityStmt, modifyDexterity, arg.ID, arg.Username)
	return err
}

const modifyIntelligence = `-- name: ModifyIntelligence :exec
INSERT INTO stats (id, username)
VALUES (?, ?)
ON CONFLICT(id) DO NOTHING
`

type ModifyIntelligenceParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) ModifyIntelligence(ctx context.Context, arg ModifyIntelligenceParams) error {
	_, err := q.exec(ctx, q.modifyIntelligenceStmt, modifyIntelligence, arg.ID, arg.Username)
	return err
}

const modifyLuck = `-- name: ModifyLuck :exec
INSERT INTO stats (id, username)
VALUES (?, ?)
ON CONFLICT(id) DO NOTHING
`

type ModifyLuckParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) ModifyLuck(ctx context.Context, arg ModifyLuckParams) error {
	_, err := q.exec(ctx, q.modifyLuckStmt, modifyLuck, arg.ID, arg.Username)
	return err
}

const modifyPenis = `-- name: ModifyPenis :exec
INSERT INTO stats (id, username)
VALUES (?, ?)
ON CONFLICT(id) DO NOTHING
`

type ModifyPenisParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) ModifyPenis(ctx context.Context, arg ModifyPenisParams) error {
	_, err := q.exec(ctx, q.modifyPenisStmt, modifyPenis, arg.ID, arg.Username)
	return err
}

const modifyStrength = `-- name: ModifyStrength :exec
INSERT INTO stats (id, username)
VALUES (?, ?)
ON CONFLICT(id) DO NOTHING
`

type ModifyStrengthParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) ModifyStrength(ctx context.Context, arg ModifyStrengthParams) error {
	_, err := q.exec(ctx, q.modifyStrengthStmt, modifyStrength, arg.ID, arg.Username)
	return err
}

const upsertStatsUser = `-- name: UpsertStatsUser :exec
INSERT INTO stats (id, username)
VALUES (?, ?)
ON CONFLICT(id) DO UPDATE SET
  username = excluded.username
`

type UpsertStatsUserParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) UpsertStatsUser(ctx context.Context, arg UpsertStatsUserParams) error {
	_, err := q.exec(ctx, q.upsertStatsUserStmt, upsertStatsUser, arg.ID, arg.Username)
	return err
}
