// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package store

import (
	"context"
)

const ensureUserStats = `-- name: EnsureUserStats :exec
INSERT INTO user_stats (user_id, username, stat_name, value)
SELECT ?, ?, sd.name, sd.default_value FROM stat_definitions sd
WHERE sd.name NOT IN (
  SELECT us.stat_name FROM user_stats us WHERE us.user_id = ?
)
`

type EnsureUserStatsParams struct {
	UserID   string `json:"userId"`
	Username string `json:"username"`
	UserID_2 string `json:"userId2"`
}

func (q *Queries) EnsureUserStats(ctx context.Context, arg EnsureUserStatsParams) error {
	_, err := q.exec(ctx, q.ensureUserStatsStmt, ensureUserStats, arg.UserID, arg.Username, arg.UserID_2)
	return err
}

const getRandomStatDefinition = `-- name: GetRandomStatDefinition :one
SELECT name, short_name, long_name, default_value, sort_order FROM stat_definitions ORDER BY RANDOM() LIMIT 1
`

func (q *Queries) GetRandomStatDefinition(ctx context.Context) (StatDefinition, error) {
	row := q.queryRow(ctx, q.getRandomStatDefinitionStmt, getRandomStatDefinition)
	var i StatDefinition
	err := row.Scan(
		&i.Name,
		&i.ShortName,
		&i.LongName,
		&i.DefaultValue,
		&i.SortOrder,
	)
	return i, err
}

const getStatDefinitions = `-- name: GetStatDefinitions :many
SELECT name, short_name, long_name, default_value, sort_order FROM stat_definitions ORDER BY sort_order
`

func (q *Queries) GetStatDefinitions(ctx context.Context) ([]StatDefinition, error) {
	rows, err := q.query(ctx, q.getStatDefinitionsStmt, getStatDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatDefinition{}
	for rows.Next() {
		var i StatDefinition
		if err := rows.Scan(
			&i.Name,
			&i.ShortName,
			&i.LongName,
			&i.DefaultValue,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatLeaderboard = `-- name: GetStatLeaderboard :many
SELECT sd.short_name, sv.username, CAST(MAX(sv.value) AS INTEGER) AS value
FROM user_stats sv
JOIN stat_definitions sd ON sv.stat_name = sd.name
GROUP BY sv.stat_name
ORDER BY sd.sort_order
`

type GetStatLeaderboardRow struct {
	ShortName string `json:"shortName"`
	Username  string `json:"username"`
	Value     int64  `json:"value"`
}

func (q *Queries) GetStatLeaderboard(ctx context.Context) ([]GetStatLeaderboardRow, error) {
	rows, err := q.query(ctx, q.getStatLeaderboardStmt, getStatLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStatLeaderboardRow{}
	for rows.Next() {
		var i GetStatLeaderboardRow
		if err := rows.Scan(&i.ShortName, &i.Username, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStats = `-- name: GetUserStats :many
SELECT sd.name, sd.short_name, sd.long_name, sv.value
FROM user_stats sv
JOIN stat_definitions sd ON sv.stat_name = sd.name
WHERE sv.user_id = ?
ORDER BY sd.sort_order
`

type GetUserStatsRow struct {
	Name      string `json:"name"`
	ShortName string `json:"shortName"`
	LongName  string `json:"longName"`
	Value     int64  `json:"value"`
}

func (q *Queries) GetUserStats(ctx context.Context, userID string) ([]GetUserStatsRow, error) {
	rows, err := q.query(ctx, q.getUserStatsStmt, getUserStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserStatsRow{}
	for rows.Next() {
		var i GetUserStatsRow
		if err := rows.Scan(
			&i.Name,
			&i.ShortName,
			&i.LongName,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modifyStatValue = `-- name: ModifyStatValue :exec
UPDATE user_stats SET value = value + ?
WHERE user_id = ? AND stat_name = ?
`

type ModifyStatValueParams struct {
	Value    int64  `json:"value"`
	UserID   string `json:"userId"`
	StatName string `json:"statName"`
}

func (q *Queries) ModifyStatValue(ctx context.Context, arg ModifyStatValueParams) error {
	_, err := q.exec(ctx, q.modifyStatValueStmt, modifyStatValue, arg.Value, arg.UserID, arg.StatName)
	return err
}

const setStatValue = `-- name: SetStatValue :exec
UPDATE user_stats SET value = ?
WHERE user_id = ? AND stat_name = ?
`

type SetStatValueParams struct {
	Value    int64  `json:"value"`
	UserID   string `json:"userId"`
	StatName string `json:"statName"`
}

func (q *Queries) SetStatValue(ctx context.Context, arg SetStatValueParams) error {
	_, err := q.exec(ctx, q.setStatValueStmt, setStatValue, arg.Value, arg.UserID, arg.StatName)
	return err
}

const updateUsername = `-- name: UpdateUsername :exec
UPDATE user_stats SET username = ? WHERE user_id = ?
`

type UpdateUsernameParams struct {
	Username string `json:"username"`
	UserID   string `json:"userId"`
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) error {
	_, err := q.exec(ctx, q.updateUsernameStmt, updateUsername, arg.Username, arg.UserID)
	return err
}
