// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package store

import (
	"context"
)

const getTokens = `-- name: GetTokens :one
SELECT access_token, refresh_token
FROM oauth_tokens
WHERE token_type = ?
`

type GetTokensRow struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

func (q *Queries) GetTokens(ctx context.Context, tokenType string) (GetTokensRow, error) {
	row := q.queryRow(ctx, q.getTokensStmt, getTokens, tokenType)
	var i GetTokensRow
	err := row.Scan(&i.AccessToken, &i.RefreshToken)
	return i, err
}

const saveTokens = `-- name: SaveTokens :exec
INSERT INTO oauth_tokens (
  token_type,
  access_token,
  refresh_token,
  updated_at
) VALUES (
  ?, ?, ?, CURRENT_TIMESTAMP
)
ON CONFLICT(token_type) DO UPDATE SET
  access_token = excluded.access_token,
  refresh_token = excluded.refresh_token,
  updated_at = CURRENT_TIMESTAMP
`

type SaveTokensParams struct {
	TokenType    string `json:"token_type"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

func (q *Queries) SaveTokens(ctx context.Context, arg SaveTokensParams) error {
	_, err := q.exec(ctx, q.saveTokensStmt, saveTokens, arg.TokenType, arg.AccessToken, arg.RefreshToken)
	return err
}
