// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_plushies.sql

package store

import (
	"context"
)

const getCollectedPlushies = `-- name: GetCollectedPlushies :many
SELECT key FROM user_plushies
WHERE user_id = ? AND series = ?
`

type GetCollectedPlushiesParams struct {
	UserID string `json:"userId"`
	Series string `json:"series"`
}

func (q *Queries) GetCollectedPlushies(ctx context.Context, arg GetCollectedPlushiesParams) ([]string, error) {
	rows, err := q.query(ctx, q.getCollectedPlushiesStmt, getCollectedPlushies, arg.UserID, arg.Series)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedCollections = `-- name: GetCompletedCollections :many
WITH completed AS (
  SELECT up.series, up.username
  FROM user_plushies up
  GROUP BY up.user_id, up.series
  HAVING COUNT(*) = (
    SELECT COUNT(*) FROM blind_box_plushies bp
    WHERE bp.series = up.series
  )
)
SELECT bbs.name AS series_name, GROUP_CONCAT(completed.username, ', ') AS usernames
FROM completed
JOIN blind_box_series bbs ON bbs.series = completed.series
GROUP BY completed.series
ORDER BY bbs.series
`

type GetCompletedCollectionsRow struct {
	SeriesName string `json:"seriesName"`
	Usernames  string `json:"usernames"`
}

func (q *Queries) GetCompletedCollections(ctx context.Context) ([]GetCompletedCollectionsRow, error) {
	rows, err := q.query(ctx, q.getCompletedCollectionsStmt, getCompletedCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCompletedCollectionsRow{}
	for rows.Next() {
		var i GetCompletedCollectionsRow
		if err := rows.Scan(&i.SeriesName, &i.Usernames); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserPlushie = `-- name: HasUserPlushie :one
SELECT EXISTS(
  SELECT 1 FROM user_plushies
  WHERE user_id = ? AND series = ? AND key = ?
) AS owned
`

type HasUserPlushieParams struct {
	UserID string `json:"userId"`
	Series string `json:"series"`
	Key    string `json:"key"`
}

func (q *Queries) HasUserPlushie(ctx context.Context, arg HasUserPlushieParams) (int64, error) {
	row := q.queryRow(ctx, q.hasUserPlushieStmt, hasUserPlushie, arg.UserID, arg.Series, arg.Key)
	var owned int64
	err := row.Scan(&owned)
	return owned, err
}

const insertUserPlushieIfNew = `-- name: InsertUserPlushieIfNew :exec
INSERT OR IGNORE INTO user_plushies (user_id, username, series, key)
VALUES (?, ?, ?, ?)
`

type InsertUserPlushieIfNewParams struct {
	UserID   string `json:"userId"`
	Username string `json:"username"`
	Series   string `json:"series"`
	Key      string `json:"key"`
}

func (q *Queries) InsertUserPlushieIfNew(ctx context.Context, arg InsertUserPlushieIfNewParams) error {
	_, err := q.exec(ctx, q.insertUserPlushieIfNewStmt, insertUserPlushieIfNew,
		arg.UserID,
		arg.Username,
		arg.Series,
		arg.Key,
	)
	return err
}

const lastChangeCount = `-- name: LastChangeCount :one
SELECT changes() AS n
`

func (q *Queries) LastChangeCount(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.lastChangeCountStmt, lastChangeCount)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const resetUserPlushies = `-- name: ResetUserPlushies :exec
DELETE FROM user_plushies
WHERE user_id = ? AND series = ?
`

type ResetUserPlushiesParams struct {
	UserID string `json:"userId"`
	Series string `json:"series"`
}

func (q *Queries) ResetUserPlushies(ctx context.Context, arg ResetUserPlushiesParams) error {
	_, err := q.exec(ctx, q.resetUserPlushiesStmt, resetUserPlushies, arg.UserID, arg.Series)
	return err
}

const upsertUserPlushie = `-- name: UpsertUserPlushie :exec
INSERT INTO user_plushies (user_id, username, series, key)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id, series, key) DO UPDATE SET
  username = excluded.username
`

type UpsertUserPlushieParams struct {
	UserID   string `json:"userId"`
	Username string `json:"username"`
	Series   string `json:"series"`
	Key      string `json:"key"`
}

func (q *Queries) UpsertUserPlushie(ctx context.Context, arg UpsertUserPlushieParams) error {
	_, err := q.exec(ctx, q.upsertUserPlushieStmt, upsertUserPlushie,
		arg.UserID,
		arg.Username,
		arg.Series,
		arg.Key,
	)
	return err
}
