// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_collections.sql

package store

import (
	"context"
	"database/sql"
)

const addReward1 = `-- name: AddReward1 :exec
INSERT INTO user_collections (
  user_id,
  username,
  collection_type,
  reward1
) VALUES (
  ?, ?, ?, 1
)
ON CONFLICT(user_id, collection_type) DO UPDATE SET
  reward1 = 1,
  username = excluded.username
`

type AddReward1Params struct {
	UserID         sql.NullString `json:"user_id"`
	Username       string         `json:"username"`
	CollectionType sql.NullString `json:"collection_type"`
}

func (q *Queries) AddReward1(ctx context.Context, arg AddReward1Params) error {
	_, err := q.exec(ctx, q.addReward1Stmt, addReward1, arg.UserID, arg.Username, arg.CollectionType)
	return err
}

const addReward2 = `-- name: AddReward2 :exec
INSERT INTO user_collections (
  user_id,
  username,
  collection_type,
  reward2
) VALUES (
  ?, ?, ?, 1
)
ON CONFLICT(user_id, collection_type) DO UPDATE SET
  reward2 = 1,
  username = excluded.username
`

type AddReward2Params struct {
	UserID         sql.NullString `json:"user_id"`
	Username       string         `json:"username"`
	CollectionType sql.NullString `json:"collection_type"`
}

func (q *Queries) AddReward2(ctx context.Context, arg AddReward2Params) error {
	_, err := q.exec(ctx, q.addReward2Stmt, addReward2, arg.UserID, arg.Username, arg.CollectionType)
	return err
}

const addReward3 = `-- name: AddReward3 :exec
INSERT INTO user_collections (
  user_id,
  username,
  collection_type,
  reward3
) VALUES (
  ?, ?, ?, 1
)
ON CONFLICT(user_id, collection_type) DO UPDATE SET
  reward3 = 1,
  username = excluded.username
`

type AddReward3Params struct {
	UserID         sql.NullString `json:"user_id"`
	Username       string         `json:"username"`
	CollectionType sql.NullString `json:"collection_type"`
}

func (q *Queries) AddReward3(ctx context.Context, arg AddReward3Params) error {
	_, err := q.exec(ctx, q.addReward3Stmt, addReward3, arg.UserID, arg.Username, arg.CollectionType)
	return err
}

const addReward4 = `-- name: AddReward4 :exec
INSERT INTO user_collections (
  user_id,
  username,
  collection_type,
  reward4
) VALUES (
  ?, ?, ?, 1
)
ON CONFLICT(user_id, collection_type) DO UPDATE SET
  reward4 = 1,
  username = excluded.username
`

type AddReward4Params struct {
	UserID         sql.NullString `json:"user_id"`
	Username       string         `json:"username"`
	CollectionType sql.NullString `json:"collection_type"`
}

func (q *Queries) AddReward4(ctx context.Context, arg AddReward4Params) error {
	_, err := q.exec(ctx, q.addReward4Stmt, addReward4, arg.UserID, arg.Username, arg.CollectionType)
	return err
}

const addReward5 = `-- name: AddReward5 :exec
INSERT INTO user_collections (
  user_id,
  username,
  collection_type,
  reward5
) VALUES (
  ?, ?, ?, 1
)
ON CONFLICT(user_id, collection_type) DO UPDATE SET
  reward5 = 1,
  username = excluded.username
`

type AddReward5Params struct {
	UserID         sql.NullString `json:"user_id"`
	Username       string         `json:"username"`
	CollectionType sql.NullString `json:"collection_type"`
}

func (q *Queries) AddReward5(ctx context.Context, arg AddReward5Params) error {
	_, err := q.exec(ctx, q.addReward5Stmt, addReward5, arg.UserID, arg.Username, arg.CollectionType)
	return err
}

const addReward6 = `-- name: AddReward6 :exec
INSERT INTO user_collections (
  user_id,
  username,
  collection_type,
  reward6
) VALUES (
  ?, ?, ?, 1
)
ON CONFLICT(user_id, collection_type) DO UPDATE SET
  reward6 = 1,
  username = excluded.username
`

type AddReward6Params struct {
	UserID         sql.NullString `json:"user_id"`
	Username       string         `json:"username"`
	CollectionType sql.NullString `json:"collection_type"`
}

func (q *Queries) AddReward6(ctx context.Context, arg AddReward6Params) error {
	_, err := q.exec(ctx, q.addReward6Stmt, addReward6, arg.UserID, arg.Username, arg.CollectionType)
	return err
}

const addReward7 = `-- name: AddReward7 :exec
INSERT INTO user_collections (
  user_id,
  username,
  collection_type,
  reward7
) VALUES (
  ?, ?, ?, 1
)
ON CONFLICT(user_id, collection_type) DO UPDATE SET
  reward7 = 1,
  username = excluded.username
`

type AddReward7Params struct {
	UserID         sql.NullString `json:"user_id"`
	Username       string         `json:"username"`
	CollectionType sql.NullString `json:"collection_type"`
}

func (q *Queries) AddReward7(ctx context.Context, arg AddReward7Params) error {
	_, err := q.exec(ctx, q.addReward7Stmt, addReward7, arg.UserID, arg.Username, arg.CollectionType)
	return err
}

const addReward8 = `-- name: AddReward8 :exec
INSERT INTO user_collections (
  user_id,
  username,
  collection_type,
  reward8
) VALUES (
  ?, ?, ?, 1
)
ON CONFLICT(user_id, collection_type) DO UPDATE SET
  reward8 = 1,
  username = excluded.username
`

type AddReward8Params struct {
	UserID         sql.NullString `json:"user_id"`
	Username       string         `json:"username"`
	CollectionType sql.NullString `json:"collection_type"`
}

func (q *Queries) AddReward8(ctx context.Context, arg AddReward8Params) error {
	_, err := q.exec(ctx, q.addReward8Stmt, addReward8, arg.UserID, arg.Username, arg.CollectionType)
	return err
}

const getCompletedCollections = `-- name: GetCompletedCollections :many
SELECT
  collection_type,
  group_concat(username, ',') AS usernames_csv
FROM user_collections
WHERE
  reward1 = 1 AND
  reward2 = 1 AND
  reward3 = 1 AND
  reward4 = 1 AND
  reward5 = 1 AND
  reward6 = 1 AND
  reward7 = 1 AND
  reward8 = 1
GROUP BY collection_type
`

type GetCompletedCollectionsRow struct {
	CollectionType sql.NullString `json:"collection_type"`
	UsernamesCsv   string         `json:"usernames_csv"`
}

func (q *Queries) GetCompletedCollections(ctx context.Context) ([]GetCompletedCollectionsRow, error) {
	rows, err := q.query(ctx, q.getCompletedCollectionsStmt, getCompletedCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompletedCollectionsRow
	for rows.Next() {
		var i GetCompletedCollectionsRow
		if err := rows.Scan(&i.CollectionType, &i.UsernamesCsv); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCollectionRow = `-- name: GetUserCollectionRow :one
SELECT user_id, username, collection_type, reward1, reward2, reward3, reward4, reward5, reward6, reward7, reward8
FROM user_collections
WHERE user_id = ?
  AND collection_type = ?
`

type GetUserCollectionRowParams struct {
	UserID         sql.NullString `json:"user_id"`
	CollectionType sql.NullString `json:"collection_type"`
}

func (q *Queries) GetUserCollectionRow(ctx context.Context, arg GetUserCollectionRowParams) (UserCollection, error) {
	row := q.queryRow(ctx, q.getUserCollectionRowStmt, getUserCollectionRow, arg.UserID, arg.CollectionType)
	var i UserCollection
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.CollectionType,
		&i.Reward1,
		&i.Reward2,
		&i.Reward3,
		&i.Reward4,
		&i.Reward5,
		&i.Reward6,
		&i.Reward7,
		&i.Reward8,
	)
	return i, err
}

const resetUserCollection = `-- name: ResetUserCollection :exec
UPDATE user_collections
SET
  reward1 = 0,
  reward2 = 0,
  reward3 = 0,
  reward4 = 0,
  reward5 = 0,
  reward6 = 0,
  reward7 = 0,
  reward8 = 0
WHERE user_id = ?
  AND collection_type = ?
`

type ResetUserCollectionParams struct {
	UserID         sql.NullString `json:"user_id"`
	CollectionType sql.NullString `json:"collection_type"`
}

func (q *Queries) ResetUserCollection(ctx context.Context, arg ResetUserCollectionParams) error {
	_, err := q.exec(ctx, q.resetUserCollectionStmt, resetUserCollection, arg.UserID, arg.CollectionType)
	return err
}
